title: "Govan Community"
email: andre.videla@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/govan_logo_small.png'
favicon: 'assets/images/favicongcc.ico'
author: andre
paginate: 30
disqus: ''
locale: en_gb
lang: en_gb
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
  # ganalytics: UA-113961478-1

# Authors
authors:
  andre:
    name: Andre Videla
    display_name: Andre Videla
    email: andre.videla@gmail.com
    web: https://andrevidela.com
  john:
    name: John Foster
    display_name: John Foster
    email: foster631@btinternet.com
  greg: 
    name: Greg Easton
    display_name: Greg Easton
    email: gregeaston@gmail.com # may want to update to a CC mailbox in the future   

# Social
social:
#   instagram: https://www.instagram.com/bootstrapstarter/
   facebook: https://www.facebook.com/profile.php?id=61571151939954
#   twitter: https://twitter.com/bstartercom

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
